using Pkg

Pkg.add("PackageCompiler")

using PackageCompiler

Pkg.activate("/jl")

# precompile_statements_file generated by ../../pl-cee498ds/precompile_statements.sh
create_sysimage(; sysimage_path="/jl_depot/sysimage.so",
    precompile_statements_file="/jl/precompile_statements.jl")